local config = require("neotest-ruby-minitest.config")
local async = require("nio.tests")

describe("config", function()
  async.it("should have default command", function()
    local conf = config.resolve()
    assert.is_string(conf.command)
    assert.are.same(conf.command, "ruby -Itest")
  end)
  async.it("should override default command", function()
    local custom_command = "custom command"
    local conf = config.resolve({ command = custom_command })
    assert.is_string(conf.command)
    assert.are.same(conf.command, custom_command)
  end)
end)
