local adapter = require("neotest-ruby-minitest")

describe('Ruby Minitest Adapter Tests', function()
    describe('Check that we can recognise correct test files', function()
        it('is_test_file', function()
            assert.is_true(adapter.is_test_file("foo_test.rb"))
            assert.is_true(adapter.is_test_file("test_foo.rb"))
            assert.is_false(adapter.is_test_file("foo.rb"))
            assert.is_true(adapter.is_test_file("nested/test_bar.rb"))
            assert.is_true(adapter.is_test_file("nested/foo_test.rb"))
        end)
    end)
end)
